# Generated by Django 5.1 on 2025-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="images/users/fazaa.png",
                upload_to="images/users/",
                verbose_name="الصورة الشخصية",
            ),
        ),
    ]
