# Generated by Django 5.1.2 on 2025-01-10 11:05

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(db_index=True, error_messages={'required': 'رقم الهاتف مطلوب', 'unique': 'هذا الرقم مستخدم من قبل'}, max_length=20, unique=True, validators=[utils.validators.validate_phone_number], verbose_name='الهاتف'),
        ),
    ]
