# Generated by Django 5.1.2 on 2024-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='code_type',
            field=models.CharField(choices=[('SIGNUP', 'Signup'), ('RESET_PASSWORD', 'Reset Password'), ('FORGET_PASSWORD', 'Forget Password')], default='SIGNUP', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('SHAREEK', 'Shareek'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20),
        ),
    ]
