# Generated by Django 5.1.2 on 2024-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode_code_type_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
