# Generated by Django 5.1.2 on 2025-03-02 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareek",
            name="job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(
                db_index=True,
                error_messages={"unique": "هذا الرقم مستخدم من قبل"},
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{7,20}$",
                        message="يجب أن يحتوي رقم الهاتف على أرقام فقط وأن يكون طوله بين 7 و 20 رقم",
                    )
                ],
                verbose_name="الهاتف",
            ),
        ),
    ]
