# Generated by Django 5.1.2 on 2025-03-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_shareek_job_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="shareek",
            options={"ordering": ["-id"]},
        ),
    ]
