# Generated by Django 5.1.2 on 2025-03-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_client_options_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usernotification",
            options={"ordering": ["-id"]},
        ),
    ]
