# Generated by Django 5.1 on 2025-06-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_first_name_user_groups_user_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
