# Generated by Django 5.1 on 2025-08-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_first_name_remove_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="images/users/placeholder.jpg",
                upload_to="images/users/",
                verbose_name="الصورة الشخصية",
            ),
        ),
    ]
