version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fazaa_web_1
    volumes:
      - .:/home/app
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    expose:
      - "8000"
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      - fazaa_network
    logging:
      options:
        max-size: 50m
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  db:
    image: postgis/postgis:15-3.3
    container_name: fazaa_db_1
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    expose:
      - "5432"
    networks:
        - fazaa_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  redis:
    image: redis:latest
    container_name: fazaa_redis_1
    ports:
      - "6380:6379"
    restart: always
    networks:
      - fazaa_network
    volumes:
      - redis_data:/data
    logging:
      options:
        max-size: 50m
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

  nginx:
    image: nginx
    build: ./nginx
    env_file:
      - ./.env
    ports:
      - "80:8080"
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always
    networks:
      - fazaa_network
    logging:
      options:
        max-size: 50m
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

networks:
  fazaa_network:
    driver: bridge

volumes:
  postgres_data:
  media_volume:
  static_volume:
  redis_data: