# Generated by Django 5.1.2 on 2025-01-06 18:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_branch_lat_remove_branch_long_branch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='الموقع'),
        ),
    ]
