# Generated by Django 5.1.2 on 2025-01-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_branch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='icon',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/images/about_us/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='icon',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/images/delivery_company/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/organizations/logos/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/images/social_media/', verbose_name='الصورة'),
        ),
    ]
