# Generated by Django 5.1.2 on 2025-01-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contactus_icon_alter_deliverycompany_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='createdAt',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='base.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='deliverycompanyurl',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='base.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='base.organization', verbose_name='المنظمة'),
        ),
    ]
