# Generated by Django 5.1.2 on 2024-12-28 16:56

import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_qr_url_organization_card_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='catalog_type',
            field=models.CharField(choices=[('MENU', 'Menu'), ('DISCOUNT', 'Discount'), ('OFFERS', 'Offers')], max_length=255, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='short_url',
            field=models.SlugField(default=utils.helper.generateShortUrl, max_length=300, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='clientoffer',
            name='content',
            field=models.CharField(max_length=500, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='clientoffer',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='clientoffer',
            name='expiresAt',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='clientoffer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='clientoffer',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.template', verbose_name='القالب'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='content',
            field=models.CharField(max_length=500, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='expiresAt',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='organizations',
            field=models.ManyToManyField(to='base.organizationtype', verbose_name='المنظمات'),
        ),
        migrations.DeleteModel(
            name='OrganizationInfoUrl',
        ),
    ]
