# Generated by Django 5.1.2 on 2024-12-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_catalog_catalog_type_alter_catalog_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationtype',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
