# Generated by Django 5.1.2 on 2025-01-03 10:34

import django.core.validators
import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_subscription_alter_catalog_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('link', models.CharField(max_length=255, verbose_name='الرابط')),
                ('icon', models.ImageField(default='images/about_us/default_about_us.png', upload_to='media/images/about_us/', verbose_name='الصورة')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='lat',
            field=models.FloatField(verbose_name='العرض'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='long',
            field=models.FloatField(verbose_name='الطول'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='commonquestion',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='الجواب'),
        ),
        migrations.AlterField(
            model_name='commonquestion',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='commonquestion',
            name='question',
            field=models.CharField(max_length=255, verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='deliverycompanyurl',
            name='active',
            field=models.BooleanField(default=False, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='deliverycompanyurl',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='deliverycompanyurl',
            name='delivery_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.deliverycompany', verbose_name='شركة التوصيل'),
        ),
        migrations.AlterField(
            model_name='deliverycompanyurl',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='deliverycompanyurl',
            name='short_url',
            field=models.SlugField(default=utils.helper.generateShortUrl, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='deliverycompanyurl',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='card_url',
            field=models.SlugField(default=utils.helper.generateShortUrl, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='commercial_register_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المعلومات التعريفية'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='media/images/organizations/logos/default.png', upload_to='media/organizations/logos/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.organizationtype', verbose_name='نوع المنظمة'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_short_url',
            field=models.SlugField(default=utils.helper.generateShortUrl, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='active',
            field=models.BooleanField(default=False, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة'),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='short_url',
            field=models.SlugField(default=utils.helper.generateShortUrl, verbose_name='الرابط المختصر'),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.socialmedia', verbose_name='موقع التواصل الاجتماعي'),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الفترة (الأيام)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الاشتراك'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(verbose_name='السعر'),
        ),
    ]
