# Generated by Django 5.1.2 on 2025-01-06 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be between 7 and 20 digits.', regex='^\\d{7,20}$')], verbose_name='الهاتف'),
        ),
    ]
