# Generated by Django 5.1.2 on 2025-01-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='الهاتف'),
        ),
    ]
