# Generated by Django 5.1.2 on 2024-12-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_shareek_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='otpcode',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
