# Generated by Django 5.1.2 on 2024-12-29 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_createat_organizationtype_createdat'),
        ('users', '0006_rename_fullname_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='shareek',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareeks', to='base.organization'),
        ),
    ]
