# Generated by Django 5.1.2 on 2025-01-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_email_alter_shareek_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
