# Generated by Django 5.1 on 2025-08-14 20:06

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                ("link", models.CharField(max_length=255, verbose_name="الرابط")),
                (
                    "icon",
                    models.ImageField(
                        default="images/default.jpg",
                        upload_to="images/about_us/",
                        verbose_name="الشعار",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CommonQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="السؤال")),
                ("answer", models.CharField(max_length=255, verbose_name="الجواب")),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                ("link", models.CharField(max_length=255, verbose_name="الرابط")),
                (
                    "icon",
                    models.ImageField(
                        default="images/default.jpg",
                        upload_to="images/about_us/",
                        verbose_name="الشعار",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                (
                    "icon",
                    models.ImageField(
                        default="images/default.jpg",
                        upload_to="images/delivery_company/",
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "icon_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/thumbnails/",
                        verbose_name="الصورة المصغرة",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commercial_register_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1000)],
                        verbose_name="رقم السجل التجاري",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        default="images/default.jpg",
                        upload_to="organizations/logos/",
                        verbose_name="الشعار",
                    ),
                ),
                (
                    "logo_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/thumbnails/",
                        verbose_name="الصورة المصغرة",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="المعلومات التعريفية",
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="الموقع الإلكتروني",
                    ),
                ),
                (
                    "website_short_url",
                    models.SlugField(
                        default=utils.helper.generateShortUrl,
                        verbose_name="اختصار الموقع الإلكتروني",
                    ),
                ),
                (
                    "card_url",
                    models.SlugField(
                        default=utils.helper.generateShortUrl,
                        verbose_name="البطاقة التعريفية",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الانشاء"
                    ),
                ),
                (
                    "website_visits",
                    models.IntegerField(default=0, verbose_name="زيارات الموقع"),
                ),
                (
                    "card_visits",
                    models.IntegerField(default=0, verbose_name="زيارات البطاقة"),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الانشاء"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                (
                    "icon",
                    models.ImageField(
                        default="images/default.jpg",
                        upload_to="images/social_",
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "icon_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/thumbnails/",
                        verbose_name="الصورة المصغرة",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الاشتراك")),
                ("price", models.FloatField(verbose_name="السعر")),
                (
                    "days",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الفترة (الأيام)",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                (
                    "template",
                    models.ImageField(
                        upload_to="images/templates/", verbose_name="القالب"
                    ),
                ),
                (
                    "template_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/thumbnails/",
                        verbose_name="الصورة المصغرة",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الانشاء"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TermsPrivacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ImageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/image_galleries/", verbose_name="الصورة"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/thumbnails/",
                        verbose_name="الصورة المصغرة",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryCompanyUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=300, null=True, verbose_name="الرابط"
                    ),
                ),
                (
                    "short_url",
                    models.SlugField(
                        default=utils.helper.generateShortUrl,
                        verbose_name="الرابط المختصر",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="مفعل")),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="محذوف")),
                ("visits", models.IntegerField(default=0, verbose_name="الزيارات")),
                (
                    "delivery_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.deliverycompany",
                        verbose_name="شركة التوصيل",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalog_type",
                    models.CharField(
                        choices=[
                            ("MENU", "Menu"),
                            ("DISCOUNT", "Discount"),
                            ("OFFERS", "Offers"),
                        ],
                        max_length=255,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="images/catalogs/", verbose_name="الملف"
                    ),
                ),
                (
                    "short_url",
                    models.SlugField(
                        default=utils.helper.generateShortUrl,
                        max_length=300,
                        verbose_name="الرابط المختصر",
                    ),
                ),
                ("visits", models.IntegerField(default=0, verbose_name="الزيارات")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogs",
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="الموقع"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="الوصف"
                    ),
                ),
                (
                    "short_url",
                    models.SlugField(
                        default=utils.helper.generateShortUrl,
                        verbose_name="الرابط المختصر",
                    ),
                ),
                ("visits", models.IntegerField(default=0, verbose_name="الزيارات")),
                ("active", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.organizationtype",
                verbose_name="نوع المنظمة",
            ),
        ),
        migrations.CreateModel(
            name="ReelsGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="images/reels_galleries/", verbose_name="الفيديو"
                    ),
                ),
                (
                    "video_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/thumbnails/",
                        verbose_name="الصورة المصغرة",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.IntegerField(verbose_name="العميل")),
                ("content", models.CharField(max_length=255, verbose_name="المحتوى")),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="المحتوى")),
                ("expiresAt", models.DateField(verbose_name="تاريخ الانتهاء")),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الانشاء"
                    ),
                ),
                ("visits", models.IntegerField(default=0, verbose_name="الزيارات")),
                (
                    "short_url",
                    models.SlugField(
                        default=utils.helper.generateShortUrl,
                        verbose_name="الرابط المختصر",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
                (
                    "organizations",
                    models.ManyToManyField(
                        to="base.organizationtype", verbose_name="المنظمات"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=300, null=True, verbose_name="الرابط"
                    ),
                ),
                (
                    "short_url",
                    models.SlugField(
                        default=utils.helper.generateShortUrl,
                        verbose_name="الرابط المختصر",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="مفعل")),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="محذوف")),
                ("visits", models.IntegerField(default=0, verbose_name="الزيارات")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
                (
                    "social_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.socialmedia",
                        verbose_name="موقع التواصل الاجتماعي",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ClientOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        default="images/default.jpg",
                        upload_to="images/client_offers/",
                        verbose_name="الغلاف",
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="المحتوى")),
                ("expiresAt", models.DateField(verbose_name="تاريخ الانتهاء")),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الانشاء"
                    ),
                ),
                (
                    "short_url",
                    models.SlugField(
                        default=utils.helper.generateShortUrl,
                        verbose_name="الرابط المختصر",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.organization",
                        verbose_name="المنظمة",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.template",
                        verbose_name="القالب",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
