# Generated by Django 5.1.2 on 2025-01-10 10:29

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='السؤال')),
                ('answer', models.CharField(max_length=255, verbose_name='الجواب')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('link', models.CharField(max_length=255, verbose_name='الرابط')),
                ('icon', models.ImageField(default='media/images/default.jpg', upload_to='media/images/about_us/', verbose_name='الشعار')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('icon', models.ImageField(default='media/images/default.jpg', upload_to='media/images/delivery_company/', verbose_name='الصورة')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_register_id', models.IntegerField(blank=True, null=True, verbose_name='رقم السجل التجاري')),
                ('logo', models.ImageField(default='media/images/default.jpg', upload_to='media/organizations/logos/', verbose_name='الشعار')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='المعلومات التعريفية')),
                ('website', models.CharField(blank=True, max_length=300, null=True, verbose_name='الموقع الإلكتروني')),
                ('website_short_url', models.SlugField(default=utils.helper.generateShortUrl, verbose_name='الرابط المختصر')),
                ('card_url', models.SlugField(default=utils.helper.generateShortUrl, verbose_name='الرابط المختصر')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('icon', models.ImageField(default='media/images/default.jpg', upload_to='media/images/social_media/', verbose_name='الصورة')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الاشتراك')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الفترة (الأيام)')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.ImageField(upload_to='media/images/templates/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/image_galleries/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCompanyUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='الرابط')),
                ('short_url', models.SlugField(default=utils.helper.generateShortUrl, verbose_name='الرابط المختصر')),
                ('active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.deliverycompany', verbose_name='شركة التوصيل')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='base.organization', verbose_name='المنظمة')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_type', models.CharField(choices=[('MENU', 'Menu'), ('DISCOUNT', 'Discount'), ('OFFERS', 'Offers')], max_length=255, verbose_name='النوع')),
                ('file', models.FileField(upload_to='media/images/catalogs/', verbose_name='الملف')),
                ('short_url', models.SlugField(default=utils.helper.generateShortUrl, max_length=300, verbose_name='الرابط المختصر')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='base.organization', verbose_name='المنظمة')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='الموقع')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.organizationtype', verbose_name='نوع المنظمة'),
        ),
        migrations.CreateModel(
            name='ReelsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/images/reels_galleries/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(verbose_name='العميل')),
                ('content', models.CharField(max_length=255, verbose_name='المحتوى')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='المحتوى')),
                ('expiresAt', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة')),
                ('organizations', models.ManyToManyField(to='base.organizationtype', verbose_name='المنظمات')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='الرابط')),
                ('short_url', models.SlugField(default=utils.helper.generateShortUrl, verbose_name='الرابط المختصر')),
                ('active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='base.organization', verbose_name='المنظمة')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.socialmedia', verbose_name='موقع التواصل الاجتماعي')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='المحتوى')),
                ('expiresAt', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization', verbose_name='المنظمة')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.template', verbose_name='القالب')),
            ],
        ),
    ]
