# Generated by Django 5.1.2 on 2025-03-02 18:05

import django.core.validators
import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagegallery",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="imagegallery",
            name="image",
            field=models.ImageField(
                upload_to="media/images/image_galleries/", verbose_name="الصورة"
            ),
        ),
        migrations.AlterField(
            model_name="imagegallery",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.organization",
                verbose_name="المنظمة",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="card_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl, verbose_name="البطاقة التعريفية"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="commercial_register_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1000)],
                verbose_name="رقم السجل التجاري",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website_short_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl,
                verbose_name="اختصار الموقع الإلكتروني",
            ),
        ),
        migrations.AlterField(
            model_name="reelsgallery",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="reelsgallery",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.organization",
                verbose_name="المنظمة",
            ),
        ),
        migrations.AlterField(
            model_name="reelsgallery",
            name="video",
            field=models.FileField(
                upload_to="media/images/reels_galleries/", verbose_name="الفيديو"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الانشاء"),
        ),
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(max_length=255, verbose_name="الاسم"),
        ),
        migrations.AlterField(
            model_name="template",
            name="template",
            field=models.ImageField(
                upload_to="media/images/templates/", verbose_name="القالب"
            ),
        ),
    ]
