# Generated by Django 5.1 on 2025-08-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientoffer",
            name="short_url",
        ),
        migrations.RemoveField(
            model_name="serviceoffer",
            name="short_url",
        ),
    ]
