# Generated by Django 5.1.2 on 2024-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='name',
        ),
        migrations.AddField(
            model_name='catalog',
            name='catalog_type',
            field=models.CharField(choices=[('MENU', 'Menu'), ('DISCOUNT', 'Discount'), ('OFFERS', 'Offers')], default='MENU', max_length=255),
            preserve_default=False,
        ),
    ]
