# Generated by Django 5.1.2 on 2025-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_imagegallery_createdat_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalog",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="clientoffer",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="commonquestion",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="deliverycompany",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="deliverycompanyurl",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="imagegallery",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="organizationtype",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="reelsgallery",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="serviceoffer",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="socialmedia",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="socialmediaurl",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="template",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="termsprivacy",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="deliverycompanyurl",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="محذوف"),
        ),
        migrations.AddField(
            model_name="socialmediaurl",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="محذوف"),
        ),
    ]
