# Generated by Django 5.1 on 2025-08-14 20:33

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_clientoffer_short_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientoffer",
            name="short_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl, verbose_name="الرابط المختصر"
            ),
        ),
        migrations.AddField(
            model_name="serviceoffer",
            name="short_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl, verbose_name="الرابط المختصر"
            ),
        ),
    ]
