# Generated by Django 5.1.2 on 2025-03-11 10:28

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_catalog_options_alter_clientoffer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="short_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl, verbose_name="الرابط المختصر"
            ),
        ),
    ]
