# Generated by Django 5.1 on 2025-08-15 17:11

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_clientoffer_short_url_serviceoffer_short_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="org_short_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl,
                verbose_name="اختصار الصفحة التعريفية ",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_visits",
            field=models.IntegerField(default=0, verbose_name="زيارات الصفحة"),
        ),
    ]
