# Generated by Django 5.1.2 on 2025-03-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_branch_short_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم")),
                ("link", models.CharField(max_length=255, verbose_name="الرابط")),
                (
                    "icon",
                    models.ImageField(
                        default="media/images/default.jpg",
                        upload_to="media/images/about_us/",
                        verbose_name="الشعار",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["-id"]},
        ),
    ]
