# Generated by Django 5.1 on 2025-09-05 08:29

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_organization_org_short_url_organization_org_visits"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="deletedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="icon",
            field=models.ImageField(
                default="images/users/fazaa.png",
                upload_to="images/about_us/",
                verbose_name="الشعار",
            ),
        ),
        migrations.AlterField(
            model_name="clientoffer",
            name="cover",
            field=models.ImageField(
                default="images/users/fazaa.png",
                upload_to="images/client_offers/",
                verbose_name="الغلاف",
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="icon",
            field=models.ImageField(
                default="images/users/fazaa.png",
                upload_to="images/about_us/",
                verbose_name="الشعار",
            ),
        ),
        migrations.AlterField(
            model_name="deliverycompany",
            name="icon",
            field=models.ImageField(
                default="images/users/fazaa.png",
                upload_to="images/delivery_company/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                default="images/users/fazaa.png",
                upload_to="organizations/logos/",
                verbose_name="الشعار",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_short_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl,
                verbose_name="رابط الصفحة التعريفية ",
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="icon",
            field=models.ImageField(
                default="images/users/fazaa.png",
                upload_to="images/social_",
                verbose_name="الصورة",
            ),
        ),
    ]
