# Generated by Django 5.1 on 2025-03-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_aboutus_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediaurl",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="الزوار"),
        ),
    ]
