# Generated by Django 5.1 on 2025-09-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_organization_deletedat_alter_aboutus_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientoffer",
            name="content",
            field=models.CharField(max_length=200, verbose_name="المحتوى"),
        ),
        migrations.AlterField(
            model_name="serviceoffer",
            name="content",
            field=models.CharField(max_length=200, verbose_name="المحتوى"),
        ),
    ]
