# Generated by Django 5.1 on 2025-09-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_clientoffer_content_alter_serviceoffer_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientoffer",
            name="template",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
