# Generated by Django 5.1 on 2025-03-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_socialmediaurl_visits"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="الزوار"),
        ),
        migrations.AddField(
            model_name="deliverycompanyurl",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="الزوار"),
        ),
    ]
