# Generated by Django 5.1 on 2025-03-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_catalog_visits_deliverycompanyurl_visits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="الزيارات"),
        ),
        migrations.AlterField(
            model_name="deliverycompanyurl",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="الزيارات"),
        ),
        migrations.AlterField(
            model_name="socialmediaurl",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="الزيارات"),
        ),
    ]
