# Generated by Django 5.1 on 2025-09-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_clientoffer_template_delete_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="reelsgallery",
            name="title",
            field=models.CharField(
                default="test", max_length=255, verbose_name="العنوان"
            ),
        ),
    ]
