# Generated by Django 5.1 on 2025-09-28 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_reelsgallery_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="GallerySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_reels",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1000)],
                    ),
                ),
                (
                    "max_images",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1000)],
                    ),
                ),
            ],
        ),
    ]
