# Generated by Django 5.1 on 2025-03-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_branch_visits_organization_visits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="visits",
        ),
    ]
