# Generated by Django 5.1 on 2025-09-28 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_gallerysetting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerysetting",
            name="max_images",
        ),
        migrations.RemoveField(
            model_name="gallerysetting",
            name="max_reels",
        ),
        migrations.AddField(
            model_name="gallerysetting",
            name="name",
            field=models.CharField(
                default="test", max_length=100, verbose_name="الاسم"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gallerysetting",
            name="value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1000)],
                verbose_name="القيمة",
            ),
        ),
    ]
