# Generated by Django 5.1 on 2025-03-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_remove_organization_visits"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientoffer",
            name="cover",
            field=models.ImageField(
                default="media/images/default.jpg",
                upload_to="media/images/client_offers/",
                verbose_name="الغلاف",
            ),
        ),
    ]
