# Generated by Django 5.1 on 2025-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_clientoffer_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="reelsgallery",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images/reels_galleries/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
    ]
