# Generated by Django 5.1 on 2025-04-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_imagegallery_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
        migrations.AlterField(
            model_name="reelsgallery",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
    ]
