# Generated by Django 5.1 on 2025-04-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_organization_logo_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverycompany",
            name="icon_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="icon_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="template_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
    ]
