# Generated by Django 5.1 on 2025-04-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_deliverycompany_icon_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="active",
            field=models.BooleanField(default=True, verbose_name="مفعل"),
        ),
        migrations.AddField(
            model_name="organization",
            name="card_visits",
            field=models.IntegerField(default=0, verbose_name="زيارات البطاقة"),
        ),
        migrations.AddField(
            model_name="organization",
            name="website_visits",
            field=models.IntegerField(default=0, verbose_name="زيارات الموقع"),
        ),
    ]
