# Generated by Django 5.1 on 2025-08-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_branch_active_organization_card_visits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceoffer",
            name="visits",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="icon",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="images/about_us/",
                verbose_name="الشعار",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="file",
            field=models.FileField(upload_to="images/catalogs/", verbose_name="الملف"),
        ),
        migrations.AlterField(
            model_name="clientoffer",
            name="cover",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="images/client_offers/",
                verbose_name="الغلاف",
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="icon",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="images/about_us/",
                verbose_name="الشعار",
            ),
        ),
        migrations.AlterField(
            model_name="deliverycompany",
            name="icon",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="images/delivery_company/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="deliverycompany",
            name="icon_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
        migrations.AlterField(
            model_name="imagegallery",
            name="image",
            field=models.ImageField(
                upload_to="images/image_galleries/", verbose_name="الصورة"
            ),
        ),
        migrations.AlterField(
            model_name="imagegallery",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="organizations/logos/",
                verbose_name="الشعار",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
        migrations.AlterField(
            model_name="reelsgallery",
            name="video",
            field=models.FileField(
                upload_to="images/reels_galleries/", verbose_name="الفيديو"
            ),
        ),
        migrations.AlterField(
            model_name="reelsgallery",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="icon",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="images/social_",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="icon_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="template",
            field=models.ImageField(
                upload_to="images/templates/", verbose_name="القالب"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="template_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/thumbnails/",
                verbose_name="الصورة المصغرة",
            ),
        ),
    ]
