# Generated by Django 5.1 on 2025-08-13 20:54

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_serviceoffer_visits_alter_aboutus_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientoffer",
            name="short_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl, verbose_name="الرابط المختصر"
            ),
        ),
        migrations.AddField(
            model_name="serviceoffer",
            name="short_url",
            field=models.SlugField(
                default=utils.helper.generateShortUrl, verbose_name="الرابط المختصر"
            ),
        ),
        migrations.AlterField(
            model_name="serviceoffer",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="الزيارات"),
        ),
    ]
