name: Deploy to old server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST2 }}
          username: ${{ secrets.USERNAME2 }}
          key: ${{ secrets.SSH_PRIVATE_KEY2 }}
          port: ${{ secrets.PORT }}
          debug: true  # Enable debug mode to get more information
          script: |
            cd /home/fazaa/Fazaa 
            git fetch origin
            git rebase origin
            docker-compose down 
            docker-compose up -d --build 